#!/bin/bash 
PACKAGE_ICON=

DNF=`dnf check-update 2>/dev/null | awk '{print $1}' | grep [.] | wc -l`

FLATPAK=$(( `flatpak update <<< "n" | wc -l` - 5 ))
(( $FLATPAK < 0 )) && FLATPAK=0

UPDATE=$(( $FLATPAK + $DNF ))
PKG=$UPDATE/`dnf list installed | wc -l`

(( $UPDATE > 5 )) && notify-send --app-name="Package Manager" --category="Package Manager" "There are $UPDATE updates available." --icon="software-update-available"
echo " $PACKAGE_ICON $PKG "
