#! /bin/bash
# panel-docker.sh - Docker panel
# @author umutsevdi 
#   A script that displays the number of active docker containers
# and their names
# @requires docker

if ! command -v docker &> /dev/null ; then
    echo "Docker doesn't exist" 1>&2
fi

count=`docker ps -q 2> /dev/null | wc -l | sed -r 's/^0$//g'`
if (( count > 0 )); then
    data=`docker ps 2> /dev/null| awk 'NR>1' | awk '{ print $2 }'  | sed -z 's/\n/ | /g'`
    data=${data::-2}
    echo "  ${data:0:20} ($count) "
else
    echo
fi
