#!/bin/bash
# panel-music.sh - Music Displayer
# @author umutsevdi 
#   A script that displays the song that is playing with 
# the singer's name 
# @requires playerctl

if ! command -v playerctl &> /dev/null ; then
    echo playerctl was not found
fi

stat=`playerctl status -s 2>/dev/null`
artist="`playerctl metadata artist -s`"
title=`playerctl metadata title -s`
if [ "$stat" = "" ]; then
    echo; exit
fi

if   [ "$artist" = "" ]; then
    current=$title
elif [ "$title" = "" ]; then
    current=$artist
else
    current="$artist - $title"
fi

start_pos=$((`date +%s` % ${#current}))  # Get the current time modulo the length of the string
end_pos=$((start_pos + 20))
if ((end_pos <= ${#current})); then
    substring="${current:start_pos:20}"
else
    overflow=$((end_pos - ${#current}))
    substring="${current:start_pos} ${current:0:overflow}"
fi

[ "$stat" = "Playing" ] && icon="󰏦 " || icon="󰐍 "
echo "$icon $substring"
